apiVersion: v2
name: helm-chart-configmirror-operator
description: A Helm chart for Kubernetes
maintainers:
  - name: bennsimon
    email: bennsimonotieno@gmail.com

type: application

version: 0.1.0

appVersion: "1.16.0"
