# This rule is not used by the project configmirror itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the bennsimon.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmirror
    app.kubernetes.io/managed-by: kustomize
  name: configmirror-editor-role
rules:
- apiGroups:
  - bennsimon.github.io
  resources:
  - configmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bennsimon.github.io
  resources:
  - configmirrors/status
  verbs:
  - get
