# This rule is not used by the project configmirror itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to bennsimon.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmirror
    app.kubernetes.io/managed-by: kustomize
  name: configmirror-viewer-role
rules:
- apiGroups:
  - bennsimon.github.io
  resources:
  - configmirrors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bennsimon.github.io
  resources:
  - configmirrors/status
  verbs:
  - get
