apiVersion: bennsimon.github.io/v1alpha1
kind: ConfigMirror
metadata:
  labels:
    app.kubernetes.io/name: configmirror
    app.kubernetes.io/managed-by: kustomize
  name: configmirror-sample-mirror
spec:
  sourceNamespace: config-mirror
  targetNamespaces:
    - default
  selector:
    matchLabels:
      app: mySvc
